
# Generated automatically by generate_docker_compose.py

version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - 15672:15672
    networks:
      - tp2-distribuidos-net

  

  ingestor:
    container_name: ingestor
    image: ingestor:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - ENTITY_NAME=ingestor
      - N_END_MESSAGES_EXPECTED=5
      - PYTHONHASHSEED=1
    volumes:
      - ./data/the-reddit-irl-dataset-comments.csv:/comments.csv
      - ./data/the-reddit-irl-dataset-posts.csv:/posts.csv
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  

  filter_posts_0:
    container_name: filter_posts_0
    image: filter_posts:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=filter_posts
      - ENTITY_SUB_ID=0
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  filter_posts_1:
    container_name: filter_posts_1
    image: filter_posts:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=filter_posts
      - ENTITY_SUB_ID=1
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  filter_comments_0:
    container_name: filter_comments_0
    image: filter_comments:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=filter_comments
      - ENTITY_SUB_ID=0
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  filter_comments_1:
    container_name: filter_comments_1
    image: filter_comments:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=filter_comments
      - ENTITY_SUB_ID=1
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  filter_comments_2:
    container_name: filter_comments_2
    image: filter_comments:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=filter_comments
      - ENTITY_SUB_ID=2
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  

  

  calculator_post_avg_score:
    container_name: calculator_post_avg_score
    image: calculator_post_avg_score:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=calculator_post_avg_score
      - N_END_MESSAGES_EXPECTED=2
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  calculator_avg_sentiment_by_post_0:
    container_name: calculator_avg_sentiment_by_post_0
    image: calculator_avg_sentiment_by_post:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=calculator_avg_sentiment_by_post
      - ENTITY_SUB_ID=0
      - N_END_MESSAGES_EXPECTED=5
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  calculator_avg_sentiment_by_post_1:
    container_name: calculator_avg_sentiment_by_post_1
    image: calculator_avg_sentiment_by_post:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=calculator_avg_sentiment_by_post
      - ENTITY_SUB_ID=1
      - N_END_MESSAGES_EXPECTED=5
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  calculator_avg_sentiment_by_post_2:
    container_name: calculator_avg_sentiment_by_post_2
    image: calculator_avg_sentiment_by_post:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=calculator_avg_sentiment_by_post
      - ENTITY_SUB_ID=2
      - N_END_MESSAGES_EXPECTED=5
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  

  joiner_0:
    container_name: joiner_0
    image: joiner_post_comment_by_id:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=joiner
      - ENTITY_SUB_ID=0
      - N_END_MESSAGES_EXPECTED_FROM_POSTS=2
      - N_END_MESSAGES_EXPECTED_FROM_COMMENTS=3
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  joiner_1:
    container_name: joiner_1
    image: joiner_post_comment_by_id:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=joiner
      - ENTITY_SUB_ID=1
      - N_END_MESSAGES_EXPECTED_FROM_POSTS=2
      - N_END_MESSAGES_EXPECTED_FROM_COMMENTS=3
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  joiner_2:
    container_name: joiner_2
    image: joiner_post_comment_by_id:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=joiner
      - ENTITY_SUB_ID=2
      - N_END_MESSAGES_EXPECTED_FROM_POSTS=2
      - N_END_MESSAGES_EXPECTED_FROM_COMMENTS=3
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  joiner_3:
    container_name: joiner_3
    image: joiner_post_comment_by_id:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=joiner
      - ENTITY_SUB_ID=3
      - N_END_MESSAGES_EXPECTED_FROM_POSTS=2
      - N_END_MESSAGES_EXPECTED_FROM_COMMENTS=3
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  joiner_4:
    container_name: joiner_4
    image: joiner_post_comment_by_id:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=joiner
      - ENTITY_SUB_ID=4
      - N_END_MESSAGES_EXPECTED_FROM_POSTS=2
      - N_END_MESSAGES_EXPECTED_FROM_COMMENTS=3
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  

  

  filter_post_max_avg_sentiment:
    container_name: filter_post_max_avg_sentiment
    image: filter_post_max_avg_sentiment:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=filter_post_max_avg_sentiment
      - N_END_MESSAGES_EXPECTED=3
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  

  filter_student_liked_posts_0:
    container_name: filter_student_liked_posts_0
    image: filter_student_liked_posts:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=filter_student_liked_posts
      - ENTITY_SUB_ID=0
      - N_END_MESSAGES_EXPECTED_FROM_POST_AVG_SCORE_CALCULATOR=1
      - N_END_MESSAGES_EXPECTED_FROM_JOINER=5
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  filter_student_liked_posts_1:
    container_name: filter_student_liked_posts_1
    image: filter_student_liked_posts:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=filter_student_liked_posts
      - ENTITY_SUB_ID=1
      - N_END_MESSAGES_EXPECTED_FROM_POST_AVG_SCORE_CALCULATOR=1
      - N_END_MESSAGES_EXPECTED_FROM_JOINER=5
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



  filter_student_liked_posts_2:
    container_name: filter_student_liked_posts_2
    image: filter_student_liked_posts:latest
    entrypoint: python3 /main.py
    environment:
      - ENTITY_NAME=filter_student_liked_posts
      - ENTITY_SUB_ID=2
      - N_END_MESSAGES_EXPECTED_FROM_POST_AVG_SCORE_CALCULATOR=1
      - N_END_MESSAGES_EXPECTED_FROM_JOINER=5
      - PYTHONHASHSEED=1
    volumes:
      - ./config/config.json:/config.json
      - ./config/pipeline.json:/pipeline.json
    depends_on:
      - rabbitmq
    networks:
      - tp2-distribuidos-net



networks:
  tp2-distribuidos-net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
